web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/topics", TopicController, :index
    get "/topics/new", TopicController, :new
    get "/topics/:id", TopicController, :show
    get "/topics/:id/edit", TopicController, :edit
    post "/topics", TopicController, :create
    put "/topics/:id", TopicController, :update
    delete "/topics/:id", TopicController, :delete
  end

  scope "/auth", Discuss do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback

  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

lib/discuss/endpoint.ex
defmodule Discuss.Endpoint do
  use Phoenix.Endpoint, otp_app: :discuss

  socket "/socket", Discuss.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :discuss, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_discuss_key",
    signing_salt: "T8XW6fDV"

  plug Discuss.Router
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss
end

web/models/comment.ex
defmodule Discuss.Comment do
    use Discuss.Web, :model

    @derive{ Poison.Encoder, only: [:content, :user] }

    schema "comments" do
        field :content, :string
        belongs_to :user, Discuss.User
        belongs_to :topic, Discuss.Topic

        timestamps()
    end

    def changeset(struct, params \\ %{}) do
        struct
        |> cast(params, [:content])
        |> validate_required([:content])
    end

end

web/models/topic.ex
defmodule Discuss.Topic do
    use Discuss.Web, :model

    schema "topics" do # look inside db and find a table called topics
        field :title, :string # we expect that table to have a single column called title with type string
        belongs_to :user, Discuss.User
        has_many :comments, Discuss.Comment
    end

    def changeset(struct, params \\ %{}) do
        struct
        |> cast(params, [:title])
        |> validate_required([:title])
    end

end

web/models/user.ex
defmodule Discuss.User do
    use Discuss.Web, :model

    @derive{ Poison.Encoder, only: [:email] }

    schema "users" do
        field :email, :string
        field :provider, :string
        field :token, :string
        has_many :topics, Discuss.Topic
        has_many :comments, Discuss.Comment

        timestamps()
    end

    def changeset(struct, params \\ %{}) do
        struct
        |> cast(params, [:email, :provider, :token])
        |> validate_required([:email, :provider, :token])
    end

end

web/controllers/auth_controller.ex
defmodule Discuss.AuthController do
    use Discuss.Web, :controller
    plug Ueberauth
    alias Discuss.User
  
    def callback(%{assigns: %{ueberauth_auth: auth}} = conn, %{"provider" => provider}) do
        user_params = %{token: auth.credentials.token, email: auth.info.email, provider: provider}
        changeset = User.changeset(%User{}, user_params)

        signin(conn, changeset)
    end

    defp signin(conn, changeset) do
        case insert_or_update_user(changeset) do
            {:ok, user} ->
                conn
                |> put_flash(:info, "welcome")
                |> put_session(:user_id, user.id)
                |> redirect(to: topic_path(conn, :index))
            {:error, _changeset} ->
                conn
                |> put_flash(:error, "oh nooo")
                |> redirect(to: page_path(conn, :index))
        end
    end

    defp insert_or_update_user(%Ecto.Changeset{changes: %{email: email}} = changeset) do
        case Repo.get_by(User, email: email) do
            nil ->
                Repo.insert(changeset)
            user ->
                {:ok, user}
        end
    end

    def signout(conn, _params) do
        conn
        |> configure_session(drop: true)
        |> put_flash(:info, "signed out")
        |> redirect(to: page_path(conn, :index))
    end
end

web/controllers/page_controller.ex
defmodule Discuss.PageController do
  use Discuss.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/topic_controller.ex
defmodule Discuss.TopicController do
    use Discuss.Web, :controller
    alias Discuss.Topic
    alias Discuss.Router.Helpers

    plug Discuss.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
    plug :check_topic_owner when action in [:edit, :update, :delete]

    def index(conn, _params) do
        topics = Repo.all(Topic)

        render conn, "index.html", topics: topics
    end

    def show(conn, %{"id" => id}) do
        topic = Repo.get!(Topic, id)

        render conn, "show.html", topic: topic
    end

    def new(conn, _params) do
        changeset = Topic.changeset(%Topic{}, %{})

        render conn, "new.html", changeset: changeset
    end

    def create(conn, %{"topic" => topic}) do
        # changeset = Topic.changeset(%Topic{}, topic)

        changeset = conn.assigns.user
            |> build_assoc(:topics)
            |> Topic.changeset(topic)

        case Repo.insert(changeset) do
            {:ok, _topic} ->
                conn
                |> put_flash(:info, "topic created")
                |> redirect(to: topic_path(conn, :index))
            {:error, changeset} -> 
                render conn, "new.html", changeset: changeset
        end
    end

    def edit(conn, %{"id" => id}) do
        topic = Repo.get(Topic, id)
        changeset = Topic.changeset(topic)

        render conn, "edit.html", changeset: changeset, topic: topic
    end

    def update(conn, %{"id" => id, "topic" => new_topic}) do
        old_topic = Repo.get(Topic, id)
        changeset = Topic.changeset(old_topic, new_topic)

        case Repo.update(changeset) do
            {:ok, _topic} ->
                conn
                |> put_flash(:info, "topic updated")
                |> redirect(to: topic_path(conn, :index))
            {:error, changeset} ->
                render conn, "edit.html", changeset: changeset, topic: old_topic
        end
    end

    def delete(conn, %{"id" => id}) do
        Repo.get!(Topic, id) |> Repo.delete!

        conn
        |> put_flash(:info, "topic deleted")
        |> redirect(to: topic_path(conn, :index))
    end

    def check_topic_owner(%{params: %{"id" => topic_id}, assigns: %{user: %Discuss.User{id: user_id}}} = conn, _params) do
        if Repo.get(Topic, topic_id).user_id == user_id do
            conn
        else
            conn
            |> put_flash(:error, "you cant do that")
            |> redirect(to: Helpers.topic_path(conn, :index))
            |> halt()
        end
    end
end

web/views/error_view.ex
defmodule Discuss.ErrorView do
  use Discuss.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

web/views/page_view.ex
defmodule Discuss.PageView do
  use Discuss.Web, :view
end

web/views/topic_view.ex
defmodule Discuss.TopicView do
    use Discuss.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(Discuss.Endpoint, "key", @conn.assigns.user.id)%>"
      <% end %>
    </script>
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          lets discuss
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "sign out", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "sign in", to: auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/topic/edit.html.eex
<h1>edit topic</h1>
<%= form_for @changeset, topic_path(@conn, :update, @topic), fn f -> %>
    <div class="form-group">
        <%= text_input f, :title, placeholder: "title", class: "form-control" %>
        <%= error_tag f, :title %>
    </div>
    
    <%= submit "Save Change", class: "btn btn-primary" %>
<% end %>

web/templates/topic/index.html.eex
<h1>topic list</h1>
<ul class="collection">
    <%= for topic <- @topics do %>
        <li class="collection-item">
            <%= link topic.title, to: topic_path(@conn, :show, topic) %>

            <%= if @conn.assigns.user.id == topic.user_id do %>
                <div class="right">
                    <%= link "edit", to: topic_path(@conn, :edit, topic) %>
                    <%= link "delete", to: topic_path(@conn, :delete, topic), method: :delete %>
                </div>
            <% end %>
        </li>
    <% end %>
</ul>

<div class="fixed-action-btn">
    <%= link to: topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
        <i class="material-icons">add</i>
    <% end %>
</div>

web/templates/topic/new.html.eex
<%# create a form using @changeset, when someone submits a form, send it to the create route thats related to topic %>
<%# form_for function eventually becomes a HTML form tag and the properties passed in to it determines where the form will be submitted to %>

<%= form_for @changeset, topic_path(@conn, :create), fn f -> %>
    <div class="form-group">
        <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
        <%= error_tag f, :title %>
    </div>

    <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

web/templates/topic/show.html.eex
<h1>
    topic ID: <%= @topic.id %>
</h1>
<h3>
    title: <%= @topic.title%>
</h3>

<div>
    <textarea class="materialize-textarea"></textarea>
    <button class="btn">add comment</button>
</div>

<ul class="collection">
</ul>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        window.createSocket(<%= @topic.id %>)
    });
</script>